/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.v3.pkg0;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author gerges Fci-H
 */
public class add_Medicine extends javax.swing.JFrame {

    /**
     * Creates new form add_Medicine
     */
    Connection con;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement stmt = null;
    
    
    public add_Medicine()  {
        con=sqlite.connectDB();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("hospital.png")));
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        showData();
        txt_id.requestFocus();
        q0.setText("0");
        
    }
    
    public void showData()
    {
        try {
            String q="select * from medicine";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_dis = new javax.swing.JTextField();
        txt_company = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ef = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_en = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tables = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_exp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_sell = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        q0 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD_Medicine");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-40.png"))); // NOI18N
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Effective:");

        txt_dis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_disActionPerformed(evt);
            }
        });
        txt_dis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_disKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_disKeyReleased(evt);
            }
        });

        txt_company.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_companyActionPerformed(evt);
            }
        });
        txt_company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_companyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_companyKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Discount:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("ID:");

        txt_ef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_ef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_efKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_efKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Ar Name:");

        txt_ar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_ar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_arKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_arKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("EN Name:");

        txt_quantity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });
        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_quantityKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Quantity:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("%");

        txt_en.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_en.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_enKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_enKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Company:");

        txt_tables.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_tables.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tablesKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tablets:");

        txt_exp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_exp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_expFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_expFocusLost(evt);
            }
        });
        txt_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_expActionPerformed(evt);
            }
        });
        txt_exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_expKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Exp Date:");

        txt_sell.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_sell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sellKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Sell price:");

        tab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EN", "AR", "Eff", "Company", "Exp", "Quantity", "Tables", "R price", "Discount", "S price", "Af Dis"
            }
        ));
        tab1.setRowHeight(30);
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        q0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        q0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q0ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Tablet Q0:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q0, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_exp)
                                        .addComponent(txt_ef)
                                        .addComponent(txt_company)
                                        .addComponent(txt_en)
                                        .addComponent(txt_ar)
                                        .addComponent(txt_quantity)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel15)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel17)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(txt_sell, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1))
                                    .addComponent(txt_tables, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_en, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_ar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ef, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tables, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_sell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(jLabel10))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        home h1=new home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_disActionPerformed

    }//GEN-LAST:event_txt_disActionPerformed

    private void txt_disKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_disKeyReleased
        
    }//GEN-LAST:event_txt_disKeyReleased

    private void txt_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_companyActionPerformed

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String sq1=txt_id.getText();
        String sq2=txt_en.getText();
        String sq3=txt_ar.getText();
        String sq4=txt_quantity.getText();
        String sq5=String.valueOf(Integer.parseInt(txt_tables.getText())*Integer.parseInt(sq4));
        String sq6=txt_ef.getText();
        String sq7=txt_company.getText();
        String sq8=txt_exp.getText();
        if(q0.getText().equals(""))
        {
            q0.setText("0");
        }
        int count=0;
        for (int i = 0; i < sq8.length(); i++) {
            if (sq8.charAt(i)=='/') {
                count++;
            }
        }
        
        String sq11=txt_sell.getText();
        String sq10=txt_dis.getText();
        String sq9=String.valueOf(Double.parseDouble(sq11)-((Double.parseDouble(sq11)*Double.parseDouble(sq10))/100));
        String sq12=txt_tables.getText();
        
        if(!sq4.equalsIgnoreCase("0"))
        {
           if(!sq8.equals("") && count !=2 )
            {
                JOptionPane.showMessageDialog(this, "Please Enter /  between Date  Like==> 1/1/2023");
            }
            else
            {
                try {
                stmt=con.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(Integer.parseInt(q0.getText())<Integer.parseInt(txt_tables.getText()))
                {
                    int tt=Integer.parseInt(sq5)+Integer.parseInt(q0.getText());
                    sq5=String.valueOf(tt);
                }
                
                String query="INSERT INTO medicine (id,en_name,ar_name,quantity,"
                        + "Tablets,effect,company,exp,retail,discount,sell,Tablets_per_box)"
                        + " VALUES ('"+sq1+"','"+sq2+"','"+sq3+"','"+sq4+"','"+sq5+"','"+sq6+"','"+sq7+"','"+sq8+"','"+sq9+"','"+sq10+"','"+sq11+"','"+sq12+"' )";
                try {
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(this, "ADD Done");
                } catch (SQLException ex) {
                    Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
        else if(sq4.equalsIgnoreCase("0") && Integer.parseInt(q0.getText())<Integer.parseInt(txt_tables.getText()))
        {
            if(!sq8.equals("") && count !=2 )
            {
                JOptionPane.showMessageDialog(this, "Please Enter /  between Date  Like==> 1/1/2023");
            }
            else
            {
                try {
                stmt=con.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
                }
                String query="INSERT INTO medicine (id,en_name,ar_name,quantity,"
                        + "Tablets,effect,company,exp,retail,discount,sell,Tablets_per_box)"
                        + " VALUES ('"+sq1+"','"+sq2+"','"+sq3+"',"
                        + "'"+sq4+"','"+q0.getText()+"',"
                        + "'"+sq6+"','"+sq7+"','"+sq8+"','"+sq9+"','"+sq10+"','"+sq11+"','"+sq12+"' )";
                try {
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(this, "ADD Done");
                } catch (SQLException ex) {
                    Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
        
        
        showData();
        txt_id.setText("");
        txt_en.setText("");
        txt_ar.setText("");
        txt_ef.setText("");
        txt_exp.setText("");
        txt_company.setText("");
        txt_dis.setText("");
        txt_tables.setText("");
        txt_sell.setText("");
        txt_quantity.setText("");
        txt_id.requestFocus();
        q0.setText("0");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        showData();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_en.requestFocus();}
    }//GEN-LAST:event_txt_idKeyPressed

    private void txt_enKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_ar.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_id.requestFocus();}
    }//GEN-LAST:event_txt_enKeyPressed

    private void txt_arKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_arKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_ef.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_en.requestFocus();}
    }//GEN-LAST:event_txt_arKeyPressed

    private void txt_efKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_company.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_ar.requestFocus();}
    }//GEN-LAST:event_txt_efKeyPressed

    private void txt_companyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_companyKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_exp.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_ef.requestFocus();}
    }//GEN-LAST:event_txt_companyKeyPressed

    private void txt_expKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_expKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_quantity.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_company.requestFocus();}
    }//GEN-LAST:event_txt_expKeyPressed

    private void txt_quantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_tables.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_exp.requestFocus();}
    }//GEN-LAST:event_txt_quantityKeyPressed

    private void txt_tablesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tablesKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_dis.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_quantity.requestFocus();}
    }//GEN-LAST:event_txt_tablesKeyPressed

    private void txt_disKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_disKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){txt_sell.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_UP){txt_tables.requestFocus();}
    }//GEN-LAST:event_txt_disKeyPressed

    private void txt_sellKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sellKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_UP){txt_dis.requestFocus();}
    }//GEN-LAST:event_txt_sellKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt_id.setText("");
        txt_en.setText("");
        txt_ar.setText("");
        txt_ef.setText("");
        txt_exp.setText("");
        txt_company.setText("");
        txt_dis.setText("");
        txt_tables.setText("");
        txt_sell.setText("");
        txt_quantity.setText("");
        q0.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_expFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_expFocusGained
        
    }//GEN-LAST:event_txt_expFocusGained

    private void txt_expFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_expFocusLost
        
    }//GEN-LAST:event_txt_expFocusLost

    private void txt_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_expActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        try {
            String q="select idope,id,en_name,ar_name,quantity,effect,Tablets"
                    + ",company,exp,retail,discount,sell,Tablets_per_box"
                    + " from medicine where id like\"%"+txt_id.getText()+"%\"";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_enKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enKeyReleased
        try {
            String q="select idope,id,en_name,ar_name,quantity,effect,Tablets"
                    + ",company,exp,retail,discount,sell,Tablets_per_box"
                    + " from medicine where en_name like\"%"+txt_en.getText()+"%\"";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_enKeyReleased

    private void txt_arKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_arKeyReleased
        try {
            String q="select idope,id,en_name,ar_name,quantity,effect,Tablets"
                    + ",company,exp,retail,discount,sell,Tablets_per_box"
                    + " from medicine where ar_name like\"%"+txt_ar.getText()+"%\"";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_arKeyReleased

    private void txt_efKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efKeyReleased
        try {
            String q="select idope,id,en_name,ar_name,quantity,effect,Tablets"
                    + ",company,exp,retail,discount,sell,Tablets_per_box"
                    + " from medicine where effect like\"%"+txt_ef.getText()+"%\"";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_efKeyReleased

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        DefaultTableModel Model =(DefaultTableModel)tab1.getModel();
        int SelectedRow =tab1.getSelectedRow();
        txt_id.setText((String) Model.getValueAt(SelectedRow,1));
        txt_en.setText((String) Model.getValueAt(SelectedRow,2));
        txt_ar.setText((String) Model.getValueAt(SelectedRow,3));
        txt_ef.setText((String) Model.getValueAt(SelectedRow,5));
        txt_tables.setText((String) Model.getValueAt(SelectedRow,12));
        txt_company.setText((String) Model.getValueAt(SelectedRow,7));
        
    }//GEN-LAST:event_tab1MouseClicked

    private void txt_companyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_companyKeyReleased
        try {
            String q="select idope,id,en_name,ar_name,quantity,effect,Tablets"
                    + ",company,exp,retail,discount,sell,Tablets_per_box"
                    + " from medicine where company like\"%"+txt_company.getText()+"%\"";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_companyKeyReleased

    private void q0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_Medicine().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField q0;
    private javax.swing.JTable tab1;
    private javax.swing.JTextField txt_ar;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_dis;
    private javax.swing.JTextField txt_ef;
    private javax.swing.JTextField txt_en;
    private javax.swing.JTextField txt_exp;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_sell;
    private javax.swing.JTextField txt_tables;
    // End of variables declaration//GEN-END:variables
}
