/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.v3.pkg0;

import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author gerges Fci-H
 */
public class sellreview extends javax.swing.JFrame {

     Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement stmt = null;
    /**
     * Creates new form sellreview
     */
    public sellreview() {
        con=sqlite.connectDB();
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("hospital.png")));
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        todayDate();
        Type.setText("Today");
        sumPrice();
        Earn();
        
    }
    
    public void showData()
    {
        try {
            String q="select * from sellReview";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            tab1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void sumPrice()
    {
        double sum = 0;
        for (int i = 0; i < tab1.getRowCount(); i++) {
            sum=sum+Double.parseDouble((String) tab1.getValueAt(i,5));
        }
        lbl_price.setText(String.format("%.2f", sum));
    }
    public double sumRetail()
    {
        double sum = 0;
        for (int i = 0; i < tab1.getRowCount(); i++) {
            sum=sum+Double.parseDouble((String) tab1.getValueAt(i,6));
        }
        return sum;
    }
    public void Earn()
    {
        double earn=Double.parseDouble(lbl_price.getText())-sumRetail();
        lbl_Earn.setText(String.format("%.2f", earn));
    }
    public void pdf() throws PrinterException
    {
        DefaultTableModel Model =(DefaultTableModel)tab1.getModel();        
        tab1.print();        
    }
    public void todayDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd/MM/yyyy");
        String Date1=s.format(d);
        
        try {
                String q="select * from sellReview where Date like \"%"+Date1+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_To = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_From = new javax.swing.JTextField();
        Combo_search = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Earn = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Type = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sell_Review");

        tab1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "operation id", "ID", "Ar Name", "En Name", "Quantity", "R price", "S price", "C Dis", "P Dis", "Date", "User"
            }
        ));
        tab1.setRowHeight(36);
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search:-");

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("To:-");

        txt_To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ToActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("From:-");

        txt_From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FromActionPerformed(evt);
            }
        });

        Combo_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_search.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operation ID", "ID", "Ar_Name", "En_Name", "Quantity", "Retail", "Price", "Date", "Time", "User", "Company" }));
        Combo_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_searchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Total Sell Price:");

        lbl_price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_price.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Total Earn:");

        lbl_Earn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_Earn.setText("0.0");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-40.png"))); // NOI18N
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PDF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("TODAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ALL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Type.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_From, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_To, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Type)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_price, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Earn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Combo_search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jButton5)
                                .addComponent(Type)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_From, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addComponent(txt_To, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lbl_Earn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_price)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt_ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ToActionPerformed

    private void txt_FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FromActionPerformed

    private void Combo_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_searchActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        home h1=new home();
        new logInfo().setFlag(0);
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String search=(String) Combo_search.getSelectedItem();
        
        if(search.equalsIgnoreCase("Operation ID"))
        {
            try {
                String q="select * from sellReview where operationID="+txt1.getText()+"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("ID"))
        {
            try {
                String q="select * from sellReview where ID=\""+txt1.getText()+"\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Ar_Name"))
        {
            try {
                String q="select * from sellReview where Ar_Name like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("En_Name"))
        {
            try {
                String q="select * from sellReview where En_Name like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Quantity"))
        {
            try {
                String q="select * from sellReview where Quantity=\""+txt1.getText()+"\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Retail"))
        {
            try {
                String q="select * from sellReview where Retail like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Price"))
        {
            try {
                String q="select * from sellReview where Price like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Date"))
        {
            try {
                String q="select * from sellReview where Date like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("User"))
        {
            try {
                String q="select * from sellReview where User like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Time"))
        {
            try {
                String q="select * from sellReview where Time like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else if(search.equalsIgnoreCase("Company"))
        {
            try {
                String q="select * from sellReview where company like \"%"+txt1.getText()+"%\"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        //Operation ID, ID, Ar_Name, En_Name, Quantity, Retail, Price, Date, User
        sumPrice();
        Earn();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if(Type.getText().equals("Today"))
        {
            todayDate();
        }
        else if(Type.getText().equals("All"))
        {
            showData();
        }
        else
        {
            todayDate();
        }
        sumPrice();
         Earn();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int to=Integer.parseInt(txt_To.getText());
       int from=Integer.parseInt(txt_From.getText());
       String select=(String) Combo_search.getSelectedItem();
       String search=txt1.getText();
       if(search.equals(""))
       {
           try {
                String q="Select * From sellReview where operationID>="+from+" AND operationID<="+to+"";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
       }
       else
       {
          if(select.equals("ID"))
          {
              System.out.println("id");
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND ID like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }
          else if(select.equals("Ar_Name"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND Ar_Name like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("En_Name"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND En_Name like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("Quantity"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND Quantity like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("User"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND User like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("Company"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND Company like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("Retail"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND Retail like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }else if(select.equals("Price"))
          {
              
              try {
                String q="Select * From sellReview where operationID>="+from+""
                        + " AND operationID<="+to+" AND Price like\"%"+search+"%\" ";
                pst=con.prepareStatement(q);
                rs=pst.executeQuery();
                tab1.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
          }
          
       }
       sumPrice();
       Earn();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
             pdf();
         } catch (PrinterException ex) {
             Logger.getLogger(sellreview.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        showData();
        Type.setText("All");
        sumPrice();
        Earn();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Type.setText("Today");
        todayDate();
        sumPrice();
        Earn();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        
    }//GEN-LAST:event_tab1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel Model =(DefaultTableModel)tab1.getModel();
        int SelectedRow =tab1.getSelectedRow();
        int yesSelected=JOptionPane.showConfirmDialog(this, "Are you Sure ?!", 
                "Delete selcted Row",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //messeage
        if(yesSelected==JOptionPane.YES_OPTION)
        {
            try {
                String q="DELETE FROM sellReview WHERE operationID="+Model.getValueAt(SelectedRow,0)+"";
                pst=con.prepareStatement(q);
                pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(Type.getText().equals("Today"))
        {
            todayDate();
        }
        else if(Type.getText().equals("All"))
        {
            showData();
        }
        else
        {
            todayDate();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_search;
    private javax.swing.JLabel Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Earn;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JTable tab1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt_From;
    private javax.swing.JTextField txt_To;
    // End of variables declaration//GEN-END:variables
}
